services:
  db:
    image: postgres:16
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - pg-network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - pg-network
    depends_on:
      - db

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8082:8081"
    volumes:
      - ./stubs:/home/wiremock
    command: --port 8081 

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.2
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - "8088:8080"
    networks:
      - pg-network
    volumes:
      - keycloak_data:/opt/keycloak/data 

networks:
  pg-network:

volumes:
  db-data:
  keycloak_data:

  # backend:
  #   build:
  #     context: .
  #     dockerfile: /Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - wiremock
  #   environment:
  #     DB_HOST: db
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #     APP_PORT: ${APP_PORT}
  #     DB_PORT: ${DB_PORT}
  #     CONTRIBUINTES_API_HOST: wiremock
  #     CONTRIBUINTES_API_PORT: 8081

