version: '3.8'
services:
  db:
    image: postgres:latest
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - pg-network
    
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      env_file:
        - .env
      ports:
        - "5050:80"
      networks:
        - pg-network

networks:
  pg-network:

volumes:
  db-data: